# Only run against master
trigger:
- master
- release/*

stages:
- stage: build
  jobs:
  - job : build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: gittools.gitversion.gitversion-task.GitVersion@5
      displayName: GitVersion
      inputs:
        preferBundledVersion: false
        configFilePath: GitVersion.yml
        updateAssemblyInfo: true
    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: publish
        publishWebProjects: false
        projects: '*.csproj'
        arguments: '-o $(build.artifactstagingdirectory) -c $(BuildConfiguration)'
    - publish: $(build.artifactstagingdirectory)
      artifact: App
- stage: deploy_DEV
  displayName: deploy to DEV
  variables:
  - group: DEV Configuration
  - group: Global Configuration  
  dependsOn: build
  jobs:
  - deployment: DeployAzFunction
    displayName: deploy and configure azure function
    pool:
      vmImage: ubuntu-latest
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: App
          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: '$(AzureConnectionName)'
              Action: 'Stop Azure App Service'
              WebAppName: '$(System.TeamProject)-app-dev-we-func'
          - task: AzureFunctionApp@1
            displayName: 'Azure App Service Deploy: $(System.TeamProject)-app-dev-we-func'
            inputs:
              azureSubscription: $(AzureConnectionName)
              appType: functionApp
              appName: '$(System.TeamProject)-app-dev-we-func'
              package: '$(Pipeline.Workspace)/**/*.zip'
              AppSettings: '-APPINSIGHTS_INSTRUMENTATIONKEY "$(appinsightInstrumentationKey)" -AppStorageKey "$(storageaccountAppKey)" -AppStorageName "$(storageaccountAppName)" -AzureWebJobsStorage "$(storageaccountAppConnectionstring)" -FUNCTIONS_EXTENSION_VERSION ~2 -ServiceBusConnectionString01 "$(servicebusFunc01AutorizationConnectionString)" -ServiceBusConnectionString02 "$(servicebusFunc02AutorizationConnectionString)" -WEBSITE_CONTENTAZUREFILECONNECTIONSTRING "$(storageaccountAppConnectionstring)" -WEBSITE_CONTENTSHARE "appformation"'
              deploymentMethod: auto
          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: '$(AzureConnectionName)'
              Action: 'Start Azure App Service'
              WebAppName: '$(System.TeamProject)-app-dev-we-func'
- stage: deploy_UAT
  displayName: deploy to UAT
  variables:
  - group: UAT Configuration
  - group: Global Configuration  
  dependsOn: deploy_DEV
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/release')
  jobs:
  - deployment: DeployAzFunction
    displayName: deploy and configure azure function
    pool:
      vmImage: ubuntu-latest
    environment: UAT
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: App
          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: '$(AzureConnectionName)'
              Action: 'Stop Azure App Service'
              WebAppName: '$(System.TeamProject)-app-uat-we-func'                   
          - task: AzureFunctionApp@1
            displayName: 'Azure App Service Deploy: $(System.TeamProject)-app-uat-we-func'
            inputs:
              azureSubscription: $(AzureConnectionName)
              appType: functionApp
              appName: '$(System.TeamProject)-app-uat-we-func'
              package: '$(Pipeline.Workspace)/**/*.zip'
              AppSettings: '-APPINSIGHTS_INSTRUMENTATIONKEY "$(appinsightInstrumentationKey)" -AppStorageKey "$(storageaccountAppKey)" -AppStorageName "$(storageaccountAppName)" -AzureWebJobsStorage "$(storageaccountAppConnectionstring)" -FUNCTIONS_EXTENSION_VERSION ~2 -ServiceBusConnectionString01 "$(servicebusFunc01AutorizationConnectionString)" -ServiceBusConnectionString02 "$(servicebusFunc02AutorizationConnectionString)" -WEBSITE_CONTENTAZUREFILECONNECTIONSTRING "$(storageaccountAppConnectionstring)" -WEBSITE_CONTENTSHARE "appformation"'
              deploymentMethod: auto
          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: '$(AzureConnectionName)'
              Action: 'Start Azure App Service'
              WebAppName: '$(System.TeamProject)-app-uat-we-func'     